name: EmergencyAlertSystem
version: '${project.version}'
main: me.pancakse.emergencyalertsystemremastered.EmergencyAlertSystem
api-version: '1.20'
authors: [ Pancakse ]
description: A plugin to provide Emergency Alert Systems.
commands:
  emergency-alert-system:
    description: Issue an emergency alert.
    permission: eas
    permission-message: You cannot issue EAS warnings thy pheasant.
    usage: /emergency-alert-system issue [EAS Type] [message]
    aliases:
      - eas
permissions:
  eas.issue:
    default: OP
    description: Issue an emergency alert.