name: Build
on: [push]
jobs:
  build:

    runs-on: ubuntu-22.04
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository


    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle

      - uses: actions/checkout@v3

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Jar
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          version: mc1.20.1-0.0.2
          github-token: ${{ secrets.TOKEN }}
          loaders: |
            paper
            purpur